print("╔"+"═════════════════════════════════════"+"╗")
print("║ VEKTOREL 1. PROJE ANA MENÜ          ║")
print("║  1- HESAP MAKİNESİ                  ║")
print("║  2- MÜZİK TÜRLERİ HAKKINDA BİLGİ    ║")
print("║  3- NOT ORTALAMASI                  ║")
print("║  4- DAİRENİN ÇAP ve ALAN HESABI     ║")
print("║  5- BİLMECE OYUNU                   ║")
print("║  6- CİSMİN DÜŞME SÜRESİ             ║")
print("║  7- BOY KİLO ENDEKSİ                ║")
print("║  8- YAŞ HESABI                      ║")
print("║  9- FAİZ GETİRİSİ                   ║")
print("║  10- RİTMİK SAYMA                   ║")
print("║  11- ÇIKIŞ                          ║")
print("║            Seçimini yap:            ║")
print("╚"+"═════════════════════════════════════"+"╝")
soru=int(input("Seçimini yap:")) 
input()
