b_yazılı=int(input("Birinci yazılı notunuz nedir?"))
i_yazılı=int(input("İkinci yazılı notunuz nedir?"))
p_ödev=int(input("Performans ödevi notunuz nedir?"))
print(f"Not ortalamanız: {(b_yazılı+i_yazılı+p_ödev)/3} dir.")
input()