def bilmeceoyun():
    soru1=input("Dışarıda sağanak yağmur altında tamamen korumasız olan bir adam var fakat saçının tek bir teli dahi ıslanmadı. Neden?")
    print("CEVAP: Adam keldi :) ")
    soru2=input("En nadir bulunan kedi türünün hangisi olduğunu biliyor musun?")
    print("CEVAP: Dragon Li :) ")
    soru3=input("Uçan köpeğe ne denir? ")
    print("CEVAP: Hav-uç :)")
    soru4=input("Viyana kuşatması neden bitmiş? ")
    print("CEVAP: Atacak kuş kalmamış :)")
    soru5=input("Tükenmez kalemin ucu biterse ne olur?")
    print("CEVAP: Tükenir kalem :)")
    soru6=input("En temiz böcek hangisidir?")
    print("CEVAP: Hamam böceği :)")
    soru7=input("Hangi keseye para konmaz?")
    print("Cevap:Safra Kesesine :)")

